services:
  - type: web
    name: app  # Change this to your app name
    env: python
    plan: free  # Change to 'starter' or 'pro' for paid plans
    buildCommand: 
      - pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PORT
        value: 10000
